version: '3'
services:
  db:
    container_name: "psql"
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - ~/dbdata:/var/lib/postgresql/data

  grantomatic:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8000:8000
    environment:
      HOST: 0.0.0.0
      PORT: 8000
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: grantomatic
      DB_PORT: 5432
    links:
      - db
    depends_on:
      - db
